namespace Hexa.Services;

/// <summary>
/// 界面词表：**中文原文（界面上那一整串，含 emoji 与空格）→ English**。
///
/// 唯一真源是各个 XAML 里的中文原文，这里只做映射 —— 所以词表可以一条条加、缺一条最多是那一句没翻，
/// 不会像"把 26 个 XAML 里的字面量逐条改成资源键"那样把改动面铺满整个界面层。
/// 键必须与界面上的字面量**逐字符相同**（多一个空格就查不到）；<see cref="LocalizationService.Apply"/>
/// 只做整串精确匹配，绝不做子串替换。
/// </summary>
public static class LocalizationTable
{
    /// <summary>
    /// 词条（顺序无关）。键重复由单元测试守住 —— 这里用数组而不是字典字面量，
    /// 就是为了让"重复键"变成一条可读的失败断言，而不是静态构造时抛 TypeInitializationException。
    /// </summary>
    public static readonly (string Zh, string En)[] Entries =
    [
        // ── 主窗口：侧栏 8 个导航按钮 ─────────────────────────────────
        ("🎮  游玩", "🎮  Playground"),
        ("🕹  手动动轴", "🕹  Manual axes"),
        ("🎯  动作", "🎯  Moves"),
        ("✍  脚本制作", "✍  Script editor"),
        ("🤖  AI 助手", "🤖  AI assistant"),
        ("📚  脚本库", "📚  Script library"),
        ("⚙️  设置", "⚙️  Settings"),
        ("🧪  测试台", "🧪  Test bench"),

        // ── 主窗口：连接 / 安全 / 为什么不动 三行 + 归中·急停 ──────────
        ("未连接", "Not connected"),
        ("⬆  全部归中", "⬆  Center all"),
        ("全部归中", "Center all"),
        ("⛔  锁定急停", "⛔  Emergency stop"),
        ("⛔  已急停（点归中解锁）", "⛔  E-stop engaged (Center all to unlock)"),
        ("设备处于急停时会解除急停并重新使能输出",
            "Centering also releases the emergency stop and re-enables output"),
        ("设备处于急停锁定，归中会解除急停并重新使能输出，是否继续？",
            "The device is locked by the emergency stop. Centering releases the stop and re-enables output. Continue?"),
        ("解除急停", "Release the emergency stop"),
        ("输出已锁（点全部归中解锁）", "Output locked (Center all to unlock)"),
        ("游戏已连（{0}）", "Game connected ({0})"),
        ("桥开着·等游戏连", "Bridge idle · waiting for a game"),
        ("最近：", "Last: "),

        // ── 引擎状态词（主窗口/手动动轴页的状态行）──────────────────────
        ("急停锁定", "E-stop engaged"),
        ("安全归中中", "Centering"),
        ("已解锁", "Unlocked"),
        ("运行中", "Running"),
        ("脚本播放", "Script playback"),
        ("游戏遥测", "Game telemetry"),
        ("游戏伴随", "Game companion"),
        ("自动动作", "Auto motion"),
        ("动作播放", "Preset playback"),
        ("挑逗", "Tease"),
        ("声音响应", "Sound reactive"),
        ("游戏桥", "Game bridge"),
        ("网页遥控器", "Web remote"),
        ("手柄", "Gamepad"),
        ("编排预览", "Editor preview"),
        ("AI 助手", "AI assistant"),
        ("归中", "Centering"),
        ("过渡中", "Easing"),
        ("待机", "Idle"),

        // ── 游玩页 ────────────────────────────────────────────────────
        ("🎮 游玩", "🎮 Playground"),
        ("自动模式内部参数：节奏、动作时长、随机池",
            "Auto mode internals: tempo, move duration, random pool"),
        ("快速预设", "Quick presets"),
        ("选好舒适档，点一个快速预设就能开始；想自己调就改下面的波形 / 强度 / 速度。",
            "Pick a comfort level and a quick preset to start; adjust wave / intensity / speed below to fine-tune."),
        ("点一下立刻开始；高亮的就是正在用的那一套。",
            "Click to start right away; the highlighted one is active."),
        ("舒适档", "Comfort level"),
        ("波形", "Wave"),
        ("强度", "Intensity"),
        ("速度", "Speed"),
        ("整体快慢（和上面显示的实时节奏是同一件事）",
            "Overall speed (the same thing as the live tempo shown above)"),
        ("动作幅度；当前舒适档会给它一个上限", "Motion range; the comfort level caps it"),
        ("节奏（BPM）", "Tempo (BPM)"),
        ("快慢范围", "Tempo range"),
        ("拖动左右两个圆点，分别设最慢 / 最快的节奏（滚轮可微调）",
            "Drag the two handles to set the slowest / fastest tempo (mouse wheel fine-tunes)"),
        ("动作切换", "Moves"),
        ("动作时长", "Move duration"),
        ("一个动作最短 / 最长做多久（滚轮可微调）",
            "Shortest / longest time per move (mouse wheel fine-tunes)"),
        ("衔接时长", "Transition"),
        ("换动作时平滑接上的时间，越长越柔和",
            "How long moves crossfade into each other; longer is smoother"),
        ("变速快慢", "Tempo change rate"),
        ("让节奏一直小幅变化（关掉 = 只在换动作时才变）",
            "Keep the tempo drifting (off = it only changes when the move does)"),
        ("开启上面那项后，节奏每秒变多少（越大越跳）；关掉那项时这项不起作用",
            "How much the tempo drifts per second while the option above is on (no effect when it is off)"),
        ("▶ 开始自动", "▶ Start auto"),
        ("↻ 换个动作", "↻ Change move"),
        ("⤓ 换温和动作 20 秒", "⤓ Gentler move for 20 s"),
        ("⏸ 锁住动作", "⏸ Lock move"),
        ("立刻换成另一个动作（要先点下面的「开始自动」）",
            "Switch to another move right away (click Start auto below first)"),
        ("锁住现在的动作不让它自己换，再点一次解锁（要先点下面的「开始自动」）",
            "Freeze the current move so it stops switching; click again to unlock (click Start auto below first)"),
        ("换成温和波浪、强度降一点，20 秒后回到随机动作（它不会让设备停下；要停点「⏹ 停止自动」或侧栏急停）",
            "Crossfades to a gentle wave at lower intensity, then back to random moves after 20 s (it does not stop the device; use Stop auto or the sidebar e-stop)"),
        ("还没开始", "Not running"),
        ("👆 跟着点", "👆 Tap along"),
        ("跟着音乐点 4 下以上，Hexa 就按你点的快慢来",
            "Tap along with the music 4+ times and Hexa follows your tempo"),
        ("跟着音乐点 4 下以上，Hexa 就把「速度」调成你的节拍（BPM = 每分钟节拍数）。",
            "Tap 4+ times with the music and Hexa sets Speed to your beat (BPM = beats per minute)."),
        ("设备实时状态", "Live device state"),
        ("下面就是设备的真实姿态，动作时会跟着动。",
            "This is the device's real pose; it follows the motion."),
        ("▸ 🕹 游戏手柄", "▸ 🕹 Gamepad"),
        ("启用手柄", "Enable gamepad"),
        ("⚠ 启用后，你动手柄设备就会跟着动。", "⚠ Once enabled, the device follows your gamepad."),
        ("没启用：手柄不影响设备；要用时点开",
            "Off: the gamepad does not drive the device; expand to enable"),
        ("还没检测（插上手柄后点下面的按钮）",
            "Not detected yet (plug in a gamepad and click the button below)"),
        ("两个摇杆 = 四个副轴", "Both sticks = four secondary axes"),
        ("左 / 右扳机 = 主行程与扭转", "Left / right trigger = stroke and twist"),
        ("▸ 🌉 游戏桥", "▸ 🌉 Game bridge"),
        ("▸ 自由游玩参数", "▸ Free-play parameters"),
        ("按上面的动作 / 强度 / 速度开始（再点一次停止）",
            "Starts with the move / intensity / speed above (click again to stop)"),
        ("参与随机的动作", "Moves in the random pool"),
        ("全选 / 全不选", "Select all / none"),
        ("全部参与", "All included"),

        // ── 手动动轴页 ────────────────────────────────────────────────
        ("🕹 手动动轴", "🕹 Manual axes"),
        ("🔒 先开开关，设备才会听你的", "🔒 Turn this on first — only then will the device obey"),
        ("允许手动动轴", "Allow manual axis control"),
        ("不勾的话滑杆是灰的，本页一条指令都不会发给设备",
            "While unchecked the sliders stay grey and this page sends nothing to the device"),
        ("默认是关的，怕你误碰。勾上之后滑杆才推得动设备；一取消勾选、离开这个页面、或者按急停，都会立刻停手 —— 设备就停在原地，不会自己跑回中间。",
            "Off by default so you cannot bump it by accident. Only when checked do the sliders drive the device; unchecking it, leaving this page or hitting the e-stop stops immediately — the device stays where it is and does not return to center."),
        ("拖左边的滑杆，六根轴就跟着你的手走，右边那台 3D 模型同时动。只在这个页面有效：一离开页面、或者取消「允许手动动轴」，设备立刻停手、停在原地。",
            "Drag the sliders on the left and all six axes follow your hand while the 3D model moves along. This works on this page only: leaving it, or unchecking Allow manual axis control, stops the device where it is."),
        ("六根轴", "Six axes"),
        ("0 = 一端，9999 = 另一端，5000 = 正中间。拖的时候设备跟着走，右边的数字就是现在发出去的值。",
            "0 = one end, 9999 = the other, 5000 = dead center. The device follows as you drag; the number on the right is the value being sent."),
        ("⟲ 全部归中", "⟲ Center all"),
        ("六根轴一起回到正中间（5000）。走安全限速、不猛冲，也不会弹窗问你",
            "Brings all six axes back to center (5000) through the safety rate limit — no jerking, no dialog"),
        ("⛔ 立刻急停", "⛔ Emergency stop"),
        ("一键停住并锁死设备。要再动它，得到侧栏点「⬆ 全部归中」解锁（会先问你一次）",
            "Stops and locks the device in one click. To move it again, click Center all in the sidebar to unlock (it asks first)"),
        ("〰 让它自己摆（正弦）", "〰 Let it swing (sine)"),
        ("▶ 开始摆动", "▶ Start swinging"),
        ("开始后设备按上面的幅度一直摆，直到你按「■ 停止」、取消勾选或离开这个页面",
            "Once started, the device keeps swinging at the range above until you press Stop, uncheck the box, or leave this page"),
        ("每秒摆多少个来回（次/秒）：0.05 = 慢悠悠，2.0 = 比较快",
            "Swings per second: 0.05 = slow and dreamy, 2.0 = fairly quick"),
        ("▸ 每根轴的幅度（进阶）", "▸ Per-axis range (advanced)"),
        ("展开后可以给每根轴单独设摆动幅度：0% = 这根轴不参与",
            "Expand to set the swing range per axis: 0% = that axis stays out"),
        ("每根轴摆多大：0% = 这根轴不参与（不动），100% = 从一端摆到另一端。",
            "How far each axis swings: 0% = out (it does not move), 100% = all the way from end to end."),
        ("🧊 实时 3D 模型", "🧊 Live 3D model"),
        ("下面就是设备真实的姿态，拖滑杆它跟着动。鼠标左键拖动可以换角度看。",
            "This is the device's real pose; it follows the sliders. Drag with the left mouse button to orbit the view."),
        ("现在在驱动设备的是：—", "Driving the device now: —"),

        // ── 脚本库页 ──────────────────────────────────────────────────
        ("📚 脚本库", "📚 Script library"),
        ("▶ 播放", "▶ Play"),
        ("⏸ 暂停", "⏸ Pause"),
        ("⏹ 停止", "⏹ Stop"),
        ("▶ 载入并播放", "▶ Load and play"),
        ("▶ 跟着播放器走", "▶ Follow the player"),
        ("连接", "Connect"),
        ("未连接 · 点「连接」开始跟随", "Not connected · click Connect to follow"),
        ("时间码偏移", "Timecode offset"),
        // 这条里有 Windows 管道名（\\.\pipe\mpvpipe）：用逐字字符串写，免得反斜杠被 C# 转义一次、
        // 与 XAML 里的原文对不上（对不上 = 这条永远不会命中）。
        (@"选你正在用的播放器，让脚本跟着它的时间码走。需要播放器开着并且允许远程控制：mpv 要用 --input-ipc-server=\\.\pipe\mpvpipe 启动；MPC-HC/BE 要在「选项 → 播放器 → Web 界面」打开（端口 13579）；VLC 要用 --extraintf http 启动（端口 8080，不设密码）。",
            @"Pick the player you use so the script follows its timecode. The player must be running and allow remote control: start mpv with --input-ipc-server=\\.\pipe\mpvpipe; in MPC-HC/BE enable Options → Player → Web interface (port 13579); start VLC with --extraintf http (port 8080, no password)."),
        ("画面和动作对不齐时调它：正值 = 脚本比画面晚一点动（设备慢半拍），负值 = 脚本早一点动。单位毫秒。",
            "Tune this when the picture and the motion drift apart: positive = the script runs slightly late (the device lags), negative = it runs early. In milliseconds."),
        ("✨ 播放增强", "✨ Playback enhancements"),
        ("三个开关默认全关，只改播放时的动作、不动脚本文件，勾上才生效。",
            "All three are off by default; they change playback only and never touch the script file."),
        ("多轴联动", "Multi-axis linking"),
        ("只动脚本自己没写动作的轴：写了的轴是作者的意图，Hexa 不会去改它",
            "Only moves the axes the script leaves out: the ones it drives are the author's intent and Hexa leaves them alone"),
        ("联动幅度", "Link amount"),
        ("脚本没写的其余轴跟着主轴一起动，30% 左右最自然。",
            "Axes the script leaves out follow the main axis; around 30% feels most natural."),
        ("其他轴最多偏离中位多少（占轴行程的百分比）。越大越明显，30% 左右比较自然",
            "How far the other axes stray from center (percent of travel). Bigger is more obvious; around 30% feels natural"),
        ("脚本平滑", "Script smoothing"),
        ("动作点之间走圆角，换向不再硬折返。",
            "Rounds off the corners between action points so reversals are no longer hard turns."),
        ("平滑强度", "Smoothing strength"),
        ("100% = 完全平滑；0% = 和以前完全一样（直线插值）。播放中直接拖动就能听出区别",
            "100% = fully smoothed; 0% = exactly as before (straight interpolation). Drag it during playback and you can hear the difference"),
        ("空档填缝", "Gap filling"),
        ("长时间不动的段落，有声音时才补小动作。",
            "Fills long still passages with small moves, but only when there is sound."),
        ("只填「两端位置几乎相同、停着超过一段时间」的段落；要有声音事件才动，安静时保持不动",
            "Only fills passages where both ends sit at nearly the same position for a while; it needs a sound event to move, and stays still when quiet"),
        ("静止超过", "Still for over"),
        ("补白幅度", "Fill amount"),
        ("空档里最多摆动多少（轴行程百分比）。它是补白，默认 20% 比较克制；调大更明显，设备换向时的余摆也更明显",
            "How far the fill swings at most (percent of travel). It is filler, so 20% is restrained by default; bigger is more obvious and leaves more overshoot when the device reverses"),
        ("连续静止超过这个时长的段落才当作空档。调小会填更多段落，调大只填很长的静止段",
            "Only still passages longer than this count as a gap. Smaller fills more passages, bigger fills only long ones"),
        ("🎵 从音频生成…", "🎵 Generate from audio…"),
        ("从音频 / 视频生成脚本", "Generate a script from audio / video"),
        ("用一首音乐或视频自动生成一份 funscript 放进脚本库；点一下在下面展开，再点收起",
            "Turns a song or video into a funscript in your library; click to expand below, click again to collapse"),
        ("选一个音乐或视频，Hexa 离线分析里面的声音（冲击 / 渐强 / 节拍），写出一份 funscript 放进脚本库。生成后可以直接在这里播放，也可以到「脚本制作 → 微调波形」继续手改。",
            "Pick a song or video and Hexa analyses the sound offline (hits / swells / beats) and writes a funscript into your library. Play it here, or keep editing it in Script editor → Wave tweak."),
        ("选择文件…", "Choose file…"),
        ("还没有选择文件", "No file chosen"),
        ("同时生成扭转轨道（R0，更立体）", "Also generate a twist track (R0, more dimensional)"),
        ("灵敏度", "Sensitivity"),
        ("越高越容易把弱一点的声音也当成事件；越低只响应明显的重音",
            "Higher treats quieter sounds as events; lower reacts only to clear accents"),
        ("▶ 开始生成", "▶ Start generating"),
        ("📑 章节 / 书签", "📑 Chapters / bookmarks"),
        ("A-B 循环", "A-B loop"),
        ("设 A", "Set A"),
        ("设 B", "Set B"),
        ("清除", "Clear"),
        ("把当前播放位置记成循环起点 A（要先把脚本放到那一点）",
            "Mark the current position as loop start A (seek there first)"),
        ("把当前播放位置记成循环终点 B；播放到 B 会自动跳回 A，一直循环",
            "Mark the current position as loop end B; playback jumps back to A and loops"),
        ("取消 A-B 循环，脚本照常从头播到尾", "Clear the A-B loop; the script plays straight through again"),
        ("脚本列表", "Script list"),
        ("名称", "Name"),
        ("时长", "Length"),
        ("轨道", "Tracks"),
        ("大小", "Size"),
        ("来源", "Source"),
        ("操作", "Actions"),
        ("🔄 刷新", "🔄 Refresh"),
        ("📂 打开库目录", "📂 Open library folder"),
        ("📥 导入脚本…", "📥 Import script…"),
        ("🔍 去社区搜", "🔍 Search the community"),
        ("📱 手机上看", "📱 View on phone"),
        ("🔍 在列表中找到它", "🔍 Find it in the list"),
        ("↻ 按文件名自动匹配脚本", "↻ Match script by file name"),
        ("📥 库里还没有脚本", "📥 No scripts in the library yet"),
        ("未载入脚本", "No script loaded"),
        ("还没有载入脚本", "Nothing loaded yet"),
        ("未设置", "Not set"),
        ("动作预设", "Move presets"),
        ("⬆ 导出", "⬆ Export"),
        ("⬇ 导入", "⬇ Import"),
        ("取消", "Cancel"),
        ("载入这个脚本并从头播放（解析不了的行不能播）",
            "Load this script and play from the start (unparsable rows cannot play)"),
        ("从脚本库里删掉它（会先问一次；不动源文件）",
            "Delete it from the library (asks first; leaves the source file alone)"),
        ("给这个脚本改名（只改库内副本）", "Rename this script (the library copy only)"),
        ("把列表滚到正在播的那一行并选中它",
            "Scroll to the row that is playing and select it"),
        ("重新读取脚本库目录（在别处新增/删除了文件时用）",
            "Re-read the library folder (after adding or deleting files elsewhere)"),
        ("在文件资源管理器里打开脚本库目录",
            "Open the library folder in File Explorer"),
        ("立刻停下设备，并把播放位置退回脚本开头（不会把设备推到脚本的起始姿态）",
            "Stops the device now and rewinds to the start of the script (it does not drive the device to the script's first pose)"),
        ("暂停 / 继续当前脚本；暂停保留进度，点「继续」从原处接着播",
            "Pause / resume the current script; pausing keeps your position and Continue picks up from there"),
        ("载入列表里选中的脚本，从头开始播放（会让设备动起来）",
            "Load the script selected in the list and play from the start (this moves the device)"),
        ("脚本倍率", "Script rate"),
        ("脚本播放倍率 +0.05x（上限 2.00x，快放）", "Playback rate +0.05x (max 2.00x, faster)"),
        ("脚本播放倍率 −0.05x（下限 0.25x，慢放）", "Playback rate −0.05x (min 0.25x, slower)"),
        ("开始读这个播放器的时间码，让脚本跟着画面走（点第二次断开）。连上之后：媒体暂停脚本也暂停、媒体快放脚本也快放、差得多就直接跳。",
            "Start reading this player's timecode so the script follows the picture (click again to disconnect). Once connected: pausing the media pauses the script, faster media plays the script faster, and a big gap makes it jump."),
        ("每行右侧可操作；鼠标停一行看明细。",
            "Use the buttons on the right of each row; hover a row for details."),
        ("点一下跳到那个时间（会让设备跳到那里）。",
            "Click to jump to that time (the device jumps there)."),
        ("下面几条任选一条，脚本就会出现在这个列表里：",
            "Do any one of these and the script shows up in this list:"),

        // ── AI 助手页外壳 ─────────────────────────────────────────────
        ("AI 用哪种性格陪你聊天，随时可换", "The personality the AI chats with — change it anytime"),
        ("当前人格", "Current persona"),
        ("👤 人格管理", "👤 Personas"),
        ("新建 / 删除人格，导入导出角色卡 JSON",
            "Create / delete personas, import and export character-card JSON"),
        ("换人格", "Switch persona"),
        ("换人格只影响 AI 说话的性格，聊天记录不会丢。上面「当前人格」里选一个即可。",
            "Switching only changes how the AI talks; the chat history stays. Just pick one under Current persona above."),
        ("⏹ 停一下（立刻停设备）", "⏹ Stop now (stops the device)"),
        ("🧹 清空对话", "🧹 Clear chat"),
        ("说点什么…（Enter 发送，Shift+Enter 换行）",
            "Say something… (Enter sends, Shift+Enter adds a line)"),
        ("AI 会自己让设备动起来。动起来之后：按左侧「⛔ 锁定急停」立刻停，或者直接对它说「停」。",
            "The AI can move the device on its own. Once it does: hit ⛔ Emergency stop on the left, or simply tell it to stop."),
        ("先填一个 API Key 就能开始", "Add an API key to get started"),
        ("去设置填 Key", "Add the key in Settings"),
        ("还没填 API Key：点上方的「去设置填 Key」填好就能发",
            "No API key yet: click Add the key in Settings above and you can start sending"),
        ("它会自己挑场景、调速度、改节奏；说得越具体，动作越合你意。下面是几句可以直接点来试的：",
            "It picks the scene, speed and rhythm on its own; the more specific you are, the better the motion fits. Here are a few lines you can click to try:"),
        ("想让设备怎么动，直接说就行", "Just say how you want the device to move"),
        ("现在设备是什么状态？", "What is the device doing right now?"),
        ("换个节奏玩玩", "Try a different rhythm"),
        ("慢一点，温柔些", "Slower and gentler"),
        ("↓ 最新消息", "↓ Latest message"),
        ("正在思考…（要中止就点下面「取消」）", "Thinking… (click Cancel below to stop)"),
        ("✅ 现在执行", "✅ Run it now"),
        ("✋ 不要", "✋ No thanks"),
        ("不用等这 3 秒，立刻就开始", "Skip the 3-second wait and start now"),
        ("取消这个动作：AI 会知道你拒绝了，会换一个更温和的做法",
            "Cancels the motion: the AI knows you refused and will pick something gentler"),
        ("💾 保存为文件", "💾 Save to file"),
        ("📋 复制", "📋 Copy"),
        ("把上面的人格 JSON 保存为 .json 文件", "Save the persona JSON above as a .json file"),
        ("把上面的人格 JSON 复制到剪贴板", "Copy the persona JSON above to the clipboard"),
        ("名字", "Name"),
        ("＋ 保存为新人格", "＋ Save as new persona"),
        ("📤 导出当前人格", "📤 Export persona"),
        ("📥 导入并应用", "📥 Import and apply"),
        ("🗑 删除当前人格", "🗑 Delete persona"),
        ("角色卡 JSON（导入 / 导出）", "Character card JSON (import / export)"),
        ("只能删自己新建/导入的人格；删除前会再确认一次",
            "Only personas you created or imported can be deleted; it asks once more before deleting"),
        ("清空这里的聊天记录（会再确认一次；设备保持当前状态，不会停）",
            "Clears the chat history here (it asks once more; the device keeps doing whatever it is doing)"),
        ("让 AI 立刻闭嘴（打断正在播放的语音）；没在说话时按钮是灰的",
            "Makes the AI shut up right away (cuts off the voice); the button is grey while it is not talking"),
        ("回到最新一条消息", "Back to the latest message"),
        ("立刻停住设备（不是发消息）", "Stops the device right away (this does not send a message)"),

        // ── 设置页：分区标题与顶部几块 ─────────────────────────────────
        ("⚙️ 设置", "⚙️ Settings"),
        ("连接设备、限定每个轴能走多远，以及悬浮窗、热键和 AI 助手。",
            "Connect the device, limit how far each axis travels, plus the overlay, hotkeys and the AI assistant."),
        ("🔌 连接", "🔌 Connection"),
        ("🎚 轴限位", "🎚 Axis limits"),
        ("▸ 🎚 轴限位", "▸ 🎚 Axis limits"),
        ("🪟 悬浮窗", "🪟 Overlay"),
        ("⌨️ 全局热键", "⌨️ Global hotkeys"),
        ("🤖 AI 助手（API Key）", "🤖 AI assistant (API Key)"),
        ("▸ 📁 存储位置", "▸ 📁 Storage location"),
        ("▸ ℹ️ 关于与维护", "▸ ℹ️ About & maintenance"),
        ("🔧 设备自检", "🔧 Self-test"),
        ("▸ 🧩 固件设置（进阶）", "▸ 🧩 Firmware settings (advanced)"),
        ("📄 日志查看", "📄 Log viewer"),
        ("🌐 本地控制接口", "🌐 Local control API"),
        ("🌐 界面语言 / UI language", "🌐 UI language"),
        ("立即连接", "Connect now"),
        ("刷新设备", "Refresh devices"),
        ("保存限位", "Save limits"),
        ("重置为全程", "Reset to full range"),
        ("优先用有线，蓝牙当备用", "Prefer wired, Bluetooth as fallback"),
        ("打开软件时自动连接设备", "Connect automatically when Hexa starts"),
        ("主通道", "Primary port"),
        ("备用通道", "Fallback port"),
        ("启用全局热键", "Enable global hotkeys"),
        ("恢复默认", "Reset to defaults"),
        ("显示悬浮窗", "Show overlay"),
        ("不透明度", "Opacity"),
        ("小窗上显示哪些内容", "What the overlay shows"),
        ("显示模式", "Show mode"),
        ("显示速度", "Show speed"),
        ("显示强度", "Show intensity"),
        ("显示 BPM", "Show BPM"),
        ("显示连接状态", "Show connection"),
        ("校准向导", "Calibration wizard"),
        ("数据目录", "Data folder"),

        // ── 补充：设置页其余静态标签（连接卡、悬浮窗、热键、日志、存储、维护）──
        // 刻意不收：语言下拉里的「中文」——英文界面下这一项要照样写着「中文」。
        ("程序版本", "Program version"),
        ("运行环境", "Runtime environment"),
        ("模型", "Model"),
        ("接口地址", "API address"),
        ("其它设置", "Other settings"),
        ("设备与排查", "Device & troubleshooting"),
        ("还没开放", "Not available yet"),
        ("刷新", "Refresh"),
        ("打开", "Open"),
        ("打开文件", "Open file"),
        ("清空", "Clear"),
        ("浏览…", "Browse…"),
        ("重启设备", "Restart device"),
        ("读取设备信息", "Read device info"),
        ("读取设置列表", "Read settings list"),
        ("应用改动", "Apply changes"),
        ("保存到设备", "Save to device"),
        ("保存 AI 设置", "Save AI settings"),
        ("导出配置…", "Export settings…"),
        ("导入配置…", "Import settings…"),
        ("动作合成目录", "Composition folder"),
        ("脚本库目录", "Script folder"),
        ("复制全部", "Copy all"),
        ("改回 C 盘用户目录", "Back to the default folder"),
        ("换成别的目录", "Use another folder"),
        ("重新读一遍日志文件", "Re-read the log file"),
        ("● 改了还没保存 —— 点「保存 AI 设置」",
            "● Changed but not saved — click Save AI settings"),
        ("版本信息 · 导出/导入设置", "Version info · export / import settings"),
        ("把当前设置打包成一个 zip 存到你想放的地方",
            "Pack the current settings into a zip wherever you like"),
        ("把现在这六个范围记住，以后开软件也是这个范围",
            "Remembers the six ranges so Hexa starts with them next time"),
        ("把最近的日志复制到剪贴板，方便发给别人看",
            "Copies the recent log to the clipboard so you can send it on"),
        ("插着 USB 线时不用蓝牙，连得更稳",
            "Skips Bluetooth while a USB cable is plugged in — a steadier link"),
        ("当前是模拟设备（未连接真实硬件）· 点这里退出模拟",
            "Simulation mode (no real hardware) · click to exit"),
        ("退出模拟设备，回到真实串口连接", "Leave simulation mode and go back to the real serial port"),
        ("跟着提示一步步测每个轴的实际边界（会让设备动起来）",
            "Step-by-step guide to measure each axis's real limits (this moves the device)"),
        ("还没读取。先连上设备，再点「读取设置列表」。",
            "Not read yet. Connect the device first, then click Read settings list."),
        ("六个轴一起回到中间位置（会让设备动起来）",
            "Brings all six axes back to center (this moves the device)"),
        ("七条命令的热键都改回出厂设置", "Resets all seven hotkeys to the factory defaults"),
        ("日志里记录窗口标题（默认关：标题会暴露你在看什么）",
            "Log window titles (off by default: titles reveal what you were watching)"),
        ("数字越小越透明，越不挡画面", "Lower is more transparent and hides less of the picture"),
        ("拖动圆点时让设备跟着动", "Move the device while you drag the handles"),
        ("限定每个轴能走的最大范围；六个轴都生效、所有页面共用",
            "Caps how far each axis may travel; applies to all six axes and every page"),
        ("要用的模型名字，填服务商给的那个名字",
            "The model to use — copy the name your provider gives you"),
        ("用记事本打开完整的日志文件", "Open the full log file in Notepad"),
        ("在文件管理器里打开这个目录", "Open this folder in File Explorer"),
        ("在文件管理器里打开这个目录（设置文件就在里面）",
            "Open this folder in File Explorer (the settings file is in there)"),
        ("这些程序会独占串口，导致 Hexa 连不上设备。",
            "These programs hold the serial port and stop Hexa from connecting."),
        ("重新扫描现在插着的串口（刚插上设备时点一下）",
            "Rescan the ports that are plugged in now (click after plugging the device in)"),
        ("主通道连不上时自动改连这个口，可以留空",
            "Falls back to this port when the primary one will not connect; may be left empty"),
        ("自动刷新（每 2 秒，排查问题时开着更方便）",
            "Auto refresh (every 2 s; handy while troubleshooting)"),

        // ── 补充：AI 助手页的静默提示与人格面板 ────────────────────────
        (" · 已中断（可能没说完）", " · Interrupted (may be cut off)"),
        (" · 正在输入…", " · Typing…"),
        ("新建人格", "New persona"),
        ("给这个人格起个名字，例如「温柔姐姐」",
            "Give this persona a name, e.g. Gentle Sister"),
        ("把角色卡的 JSON 粘到这里，再点「导入并应用」",
            "Paste the character-card JSON here, then click Import and apply"),
        ("把上面这段设定存成一个人格，并立刻切换过去",
            "Saves the text above as a persona and switches to it right away"),
        ("用这段 JSON 建一个人格并立刻切换过去",
            "Creates a persona from this JSON and switches to it right away"),
        ("不再等这次 AI 回复（正在说的话也会被打断）",
            "Stops waiting for this reply (it also cuts the AI off mid-sentence)"),
        ("当前人格的 JSON；可复制或保存为文件",
            "The current persona as JSON; copy it or save it to a file"),
        // 这条是 Style 里 DataTrigger 的 Setter Value（不是 ToolTip 属性），运行时照样落在按钮的 ToolTip 上。
        ("发送给 AI（Enter 也一样）", "Send to the AI (Enter also works)"),

        // ── 补充：脚本库页漏掉的一个静态标签 ──────────────────────────
        ("动作幅度", "Motion range"),
    ];

    /// <summary>查表用的字典（由 <see cref="Entries"/> 在静态构造时建好）。</summary>
    public static readonly Dictionary<string, string> Map = BuildMap();

    private static Dictionary<string, string> BuildMap()
    {
        var map = new Dictionary<string, string>(Entries.Length, StringComparer.Ordinal);
        foreach ((string zh, string en) in Entries) map[zh] = en;
        return map;
    }
}
